#!/usr/bin/env bash
# This script displays "Holberton School" 10 times but on the 9th iter it also displays "Hi" on a new line.
i="0"
while [ $i -lt 10 ]
do
    echo "Holberton School"
    if [ $i -eq 8 ]
    then
        echo "Hi"
    fi
    i=$((i+1))
done
