#!/usr/bin/env bash
# This script displays "bad luck" on the 4th iteration, "good luck" on the 8th iteration and "Holberton School" on the other ones (iterates 10 times).

i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    ((i=i+1))
done
