#!/usr/bin/env bash
# This script displays numbers from 1 to 20 but on number 4 it also displays "bad luck from China", number 9 "bad luck from Japan" ,and on 17 "bad luck from Italy"
i=1
while [ $i -le 20 ]
do
    echo $i
    case $i in 
        4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
    esac
    ((i=i+1))
done
