#!/usr/bin/env bash
# This script changes the /etc/hosts file. It changes localhost to 127.0.0.2 and facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.copy
echo "127.0.0.2 localhost" > ~/new_hosts
echo "8.8.8.8   facebook.com" >> ~/new_hosts
cp -f ~/new_hosts /etc/hosts
